package com.example.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val play: String,
    val characters: String,
    val stages: String,
    val games: String,
    val settings: String,
    val languageAndAppearance: String,
    val language: String,
    val english: String,
    val arabic: String,
    val themeMode: String,
    val dark: String,
    val light: String,
    val systemDefault: String,
    val primaryColor: String,
    val red: String,
    val purple: String,
    val blue: String,
    val green: String,
    val yellow: String,
    val gameDirectory: String,
    val baseEngineData: String,
    val downloadEngineDescription: String,
    val downloadBaseData: String,
    val controls: String,
    val editControllerLayout: String,
    val customizeControllerDescription: String,
    val mugenMobile: String,
    val storagePermissionRequired: String,
    val readyToFight: String,
    val start: String,
    val viewCrashLogs: String,
    val crashLogs: String,
    val close: String,
    val noCrashLogs: String
)

val EnglishStrings = AppStrings(
    play = "Play",
    characters = "Characters",
    stages = "Stages",
    games = "Games",
    settings = "Settings",
    languageAndAppearance = "Language and Appearance",
    language = "Language",
    english = "English",
    arabic = "Arabic",
    themeMode = "Theme Mode",
    dark = "Dark",
    light = "Light",
    systemDefault = "System Default",
    primaryColor = "Primary Color",
    red = "Red",
    purple = "Purple",
    blue = "Blue",
    green = "Green",
    yellow = "Yellow",
    gameDirectory = "Game Directory",
    baseEngineData = "Base Engine Data",
    downloadEngineDescription = "Download standard MUGEN system files to your local folder.",
    downloadBaseData = "Download Base Data",
    controls = "Controls",
    editControllerLayout = "Edit Controller Layout",
    customizeControllerDescription = "Customize on-screen buttons for MUGEN",
    mugenMobile = "MUGEN MOBILE",
    storagePermissionRequired = "Storage permission is required to load characters and stages.",
    readyToFight = "Ready to Fight!",
    start = "START",
    viewCrashLogs = "View Crash Logs",
    crashLogs = "Crash Logs",
    close = "Close",
    noCrashLogs = "No crash logs found."
)

val ArabicStrings = AppStrings(
    play = "العب",
    characters = "الشخصيات",
    stages = "المراحل",
    games = "الألعاب",
    settings = "الإعدادات",
    languageAndAppearance = "اللغة والمظهر",
    language = "اللغة",
    english = "الإنجليزية",
    arabic = "العربية",
    themeMode = "وضع المظهر",
    dark = "داكن",
    light = "فاتح",
    systemDefault = "النظام",
    primaryColor = "اللون الأساسي",
    red = "أحمر",
    purple = "بنفسجي",
    blue = "أزرق",
    green = "أخضر",
    yellow = "أصفر",
    gameDirectory = "مسار اللعبة",
    baseEngineData = "ملفات المحرك الأساسية",
    downloadEngineDescription = "تنزيل ملفات نظام MUGEN الأساسية إلى المجلد المحلي.",
    downloadBaseData = "تنزيل الملفات",
    controls = "التحكم",
    editControllerLayout = "تعديل أزرار التحكم",
    customizeControllerDescription = "تخصيص أزرار التحكم على الشاشة",
    mugenMobile = "MUGEN MOBILE",
    storagePermissionRequired = "صلاحية التخزين مطلوبة لتحميل الشخصيات والمراحل.",
    readyToFight = "استعد للقتال!",
    start = "ابدأ",
    viewCrashLogs = "سجلات الأعطال",
    crashLogs = "سجلات الأعطال",
    close = "إغلاق",
    noCrashLogs = "لم يتم العثور على سجلات أعطال."
)

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }
